name: Build and Version

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main, master, develop, feature ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: AutoModality/action-clean@v1
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Fetch all history
      run: |
        git fetch --prune --unshallow
        git branch -r

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.10.2
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.10.2
      with:
        useConfigFile: true
        additionalArguments: '/verbosity Diagnostic'
      id: gitversion

    - name: Display Version
      run: |
        echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
        echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
        echo "MajorMinorPatch: ${{ steps.gitversion.outputs.majorMinorPatch }}"
